Repository MightyJoeW/OpenSourceDevs, pull requests merged in 2021-10, with the labels that each got.

#1 feat: add page content
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/App.js
  src/App.test.js
  src/components/about.jsx
  src/components/dev-card.jsx
  src/components/dev-grid-utils.js
  src/components/footer.jsx
  src/components/hack.png
  src/components/help.jsx
  src/components/home.jsx
  src/components/navbar.jsx
  src/images/github-about.png
Labels: enhancement, hacktoberfest

#2 feat: add contribution steps to readme
  README.md
  src/components/help.jsx
  src/routes.js
Labels: documentation, hacktoberfest

#4 feat: added kw info
  src/components/dev-grid-utils.js
Labels: hacktoberfest

#5 fix: update links to correct open source starter guide path
  src/components/about.jsx
  src/components/footer.jsx
Labels: hacktoberfest

#6 feat: add Mariothedog dev card
  src/components/dev-grid-utils.js
Labels: hacktoberfest, hacktoberfest-accepted

#7 feat: added info for Nathan Lewis
  src/components/dev-grid-utils.js
Labels: hacktoberfest, hacktoberfest-accepted

#9 feat: Yash-271120 bio details
  src/components/dev-grid-utils.js
Labels: hacktoberfest, hacktoberfest-accepted

#11 fix: make about page image responsive with mui card
  src/components/about.jsx
  src/components/dev-grid-utils.js
Labels: hacktoberfest, hacktoberfest-accepted

#16 Added JT007-ctrl Bio details
  src/components/dev-grid-utils.js
Labels: hacktoberfest, hacktoberfest-accepted
